### ISSUE TITLE
ImportError: cannot import name 'dataset_dict' from 'data' 

### ISSUE THREAD

**Issue by Hatsune1** [yuehaowang/RecolorNeRF#1]
Hi,
Thanks for the great work!
I am trying to run your code but reported an import error as shown in the title. Also, I did not find the requested module in "Supported datasets" of readme file. 
The traceback location is shown as follow:
https://github.com/yuehaowang/RecolorNeRF/blob/3a8797711fcc6d28e5876e94ac438eb77128c1fc/engine/trainer.py#L15
Could you tell me how to find this module?

**Comment by yuehaowang** [comment]
Thank you very much for reporting this bug.
We fixed this bug by supplying the missing files.

**Comment by Hatsune1** [comment]
Thank you for your immediate update.
I met a new problem that cannot import 'searchsorted' from 'torch' with new __init__ files.
Is that a problem with wrong torch version/missing module? My torch version is 1.13.1.

**Comment by Hatsune1** [comment]
New try: report a error of missing `chardet` module. Solved by installing with:
`pip install chardet`
But there is another problem:

> Traceback (most recent call last):
  File "run_recolornerf.py", line 4, in <module>
    from engine.trainer import Trainer
  File "/home/user/Desktop/Demos/RecolorNeRF-master/engine/trainer.py", line 16, in <module>
    from models import MODEL_ZOO
  File "/home/user/Desktop/Demos/RecolorNeRF-master/models/__init__.py", line 1, in <module>
    from models.palette_tensoRF import PaletteTensorVM
  File "/home/user/Desktop/Demos/RecolorNeRF-master/models/palette_tensoRF.py", line 6, in <module>
    from .loss import soft_L0_norm
  File "/home/user/Desktop/Demos/RecolorNeRF-master/models/loss.py", line 5, in <module>
    from pytorch3d.ops import knn_points
ModuleNotFoundError: No module named 'pytorch3d'

Although I am sure that I ran `conda install pytorch3d -c pytorch3d`, pytorch3d module still isn't recognized.

**Comment by yuehaowang** [comment]
From my view, this is an issue regarding installation of PyTorch3D. You may refer to the [official installation instructions](https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md). If there are still many missing packages, re-installing the whole environment is a possible solution.
